#cloud-config
users:
  - default
  - name: nextcloud
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6Zh3s6FWjvspjmN+Lxu+txeoVsE9/uDkDGNBmha9OW9zvRkc7YWTKKWovKUS1YIhJpejVXxKa2XdAllUExU3DccF/npdg8S55Tka6OV54Ib2gF7WfdW32KcBAIlUJ28sBQ/hUAyBM5EtJFz1a1/khY9zO8vxrauODMEw5HjGraM1H4daLF1bMnhyKVTxFpBQ1yu5JtWqCM6KoTS2ujl7nrJUH2b1PibQ2KYhodCqljvBLthsuPbgFGexpdwB8DXkXLM9+x30N5oMHUnVstnQM6Ce8Da+Uj9j2NacccDUSmtNjgmnmhOZPqyYMsa9/tDelRlqh74nXNN8b0nS074adU4Zw0vLaST3iicVZCtTuzCPeigPrm4ZCsvswxK61tH95Scq+11Umbjnt6ylBgfmXWZSIFVE4WezrjukMp/WvAFNvcWyfoqem9G9vtxwDpMbbmskjsoAudKkEG3OzQ4oT36/oGmO9JLFeIqgLEdWc3JKCw1kdE4brCkeWb1asd48= delta@Laptop-Yannic

packages:
  - apache2
  - mariadb-server
  - libapache2-mod-php
  - php
  - php-gd
  - php-mysql
  - php-curl
  - php-zip
  - php-xml
  - php-mbstring

write_files:
  - path: /etc/apache2/sites-available/nextcloud.conf
    content: |
      <VirtualHost *:80>
          ServerName your_server_domain_or_IP
          DocumentRoot /var/www/html/nextcloud
          <Directory /var/www/html/nextcloud>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
              SetEnv HOME /var/www/html/nextcloud
              SetEnv HTTP_HOME /var/www/html/nextcloud
          </Directory>
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined

  - path: /etc/php/7.4/apache2/conf.d/20-nextcloud.ini
    content: |
      upload_max_filesize=512M
      post_max_size=512M
      memory_limit=512M
      max_execution_time=360

runcmd:
  - curl https://download.nextcloud.com/server/releases/latest.tar.bz2 --output /tmp/nextcloud.tar.bz2
  - tar -xvjf /tmp/nextcloud.tar.bz2 -C /var/www/html/
  - chown -R www-data:www-data /var/www/html/nextcloud/
  - chmod 755 /var/www/html/nextcloud/
  - mysql -u root -e "CREATE DATABASE nextcloud;"
  - mysql -u root -e "GRANT ALL ON nextcloud.* to 'nextcloud'@'localhost' IDENTIFIED BY 'your_password';"
  - a2enmod rewrite
  - a2ensite nextcloud.conf
  - systemctl reload apache2
