---
# tasks file for setting up a MySQL server

- name: Update system
  apt:
    upgrade: 'yes'
    update_cache: 'yes'
    cache_valid_time: 86400 # One day

- name: Install MySQL Server
  apt:
    name: 
      - mysql-server
      - python3
      - pip
    update_cache: 'yes'
    state: present
- name: Install PyMySQL
  pip:
    name: PyMySQL
    state: present

- name: copy conf file for mysql  
  ansible.builtin.copy:
    src: ./files/.my.cnf
    dest: /root/.my.cnf
    mode: "0644"
    become: true


- name: Start MySQL service and enable on startup
  service:
    name: mysql
    state: started
    enabled: 'yes'

#add the ufw rules for ssh and mysql
#set bind address for the network card

- name: Create a new database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: wow
    state: present


- name: Create MySQL user for testdb and grant all privileges
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: testuser
    password: "testpassword"
    priv: "*.*:ALL"
    state: present
    host: '%'
    append_privs: 'yes'



- name: restart mysql
  service:
    name: mysql
    state: restarted
