#cloud-config
users:
  - default
  - name: walt
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCk2pQPDL6xxeNrsB+uk19ZA+l788IYo0Gj2Ung3hM6cYN02dkGHuWDR87oi1r16sV2sPVvvePK0dfjm2uvqgqjHY4spcI+IUBzGi3lJZPT9HShUQmL+2wWDUY0kkNX1GERytEMesYVmNsBLq2YyPawf+DD2eYj89sEtZH+GUr2EOoOET2YfmL3up7B0iQJ6n69Oo0woL3tYuZwqx1WXoU4WiHmFgbTsdYIOsTbS9Z2YbMQNj5ZilTzlQD/eIqNwik6PEImpIxSPWvwFyYk0rJliLKOy3UfVgbARWfwiafDBMBtL6H8GwK0trkP+1HfO1E+Drmc34YlrJcs8IfqxNjiqCrjdArLqlj9V29K8YfUYPJ6D4Cnop0/WOZA7ITbIfQ0vPAqM0o66IxGrW++qcNRZc4J3wZKUiDO9miPrfo6EQiqPHbf5kAt/jY49kE6OSNm/rIpslfcrbbb3WhOB28rOycZtweWLU+1M1yCa7585Pt72vyscKV8e1Hc+dW4QsU= fynnk@Fynn-PrivateLaptop
packages:
  - curl
  - sudo
  - docker.io
runcmd:
  - cd /home/walt
  - sudo useradd -M -U prometheus
  - sudo useradd -M -U node_exporter
  - sudo groupadd node_exporter
  - sudo usermod -a -G node_exporter node_exporter
  - sudo apt-get install -y adduser libfontconfig1
  - wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
  - wget https://github.com/muellefy/ModulCloud/raw/main/prometheus.yml
  - wget https://raw.githubusercontent.com/muellefy/ModulCloud/main/prometheus_grafana.service
  - wget https://raw.githubusercontent.com/muellefy/ModulCloud/main/grafana_prometheus.sh
  - tar xvfz node_exporter-*.*-amd64.tar.gz
  - sudo mv /home/walt/node_exporter-*.*-amd64/node_exporter /usr/local/bin/
  - sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter
  - sudo systemctl daemon-reload
  - sudo systemctl start node_exporter
  - sudo systemctl enable node_exporter.service
  - touch test_node_exporter.txt
  - curl http://localhost:9100/metrics > test_node_exporter.txt
  - docker pull prom/prometheus
  - docker pull grafana/grafana
  - docker volume create modul-cloud 
  - sudo mv /home/walt/prometheus_grafana.service /etc/systemd/system/
  - sudo systemctl daemon-reload
  - sudo systemctl start prometheus_grafana.service
  - sudo systemctl enable prometheus_grafana.service