---
# tasks file for ./postgress


#need to be done for the postgress sever
#set new password for the wordpress user and the right privileges
# set the bind address to '*', set the pg_hba.conf to 
# host    all             all             0.0.0.0/0                       md5
#restart the service
- name: Update system
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: install PostgreSQL
  apt:
    name: 
      - postgresql
      - python3
      - pip
    state: present

- name: "Install Python packages"
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - psycopg2-binary


- name: start service
  ansible.builtin.service:
    name: postgresql.service
    state: started

- name: Add postgres user to sudo group
  become: true  # You need to become root to modify user groups
  user:
    name: postgres
    groups: sudo
    append: true  # This is important to only add the user to the sudo group, not replace the existing groups


- name: "Create app database"
  postgresql_db:
    state: present
    name: wordpress
  become: true
  become_user: postgres


- name: "Create db user"
  postgresql_user:
    state: present
    name: wordpress
    password: wordpress
  become: true
  become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: wordpress
    roles: wordpress
    grant_option: no
    privs: all
  become: true
  become_user: postgres