---
- name: Test WordPress Role
  hosts: wordpress
  become: true

  roles:
    - ./wordpress


- name: Install MySQL
  hosts: mysql
  become: true

  roles:
    - ./mysql


- name: sprengig
  hosts: nginx-reverse-proxy
  become: true

  roles:
    - ./nginx-proxy
