---
- name: Test WordPress Role
  hosts: wordpress
  become: true

  roles:
    - ./wordpress


- name: Install PostgresSql
  hosts: postgress-server
  become: true

  roles:
    - ./postgress

- name: install nginx + configure
  hosts: nginx-reverse-proxy
