#cloud-config
users:
  - default
  - name: linux
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa 
packages:
  - curl
  - sudo
  - docker.io
runcmd:
  - da sind denn all dini befehl wo du wetsch uf de vm uusfüehre